export default [
    {
        path:"/personCenter",
        name:"PersonCenter",
        component:()=>import("@/views/PersonCenter.vue"),
        meta: {
            title: '个人中心',
            authRequire:true
        },
        children:[
            {
                path:"/",
                component:()=>import("@/components/personcenter/myOrder.vue"),
                meta:{
                    title:"我的订单",
                    authRequire:true
                }
            },
            {
                path:"myorder",
                name:"myorder",
                component:()=>import("@/components/personcenter/myOrder.vue"),
                meta:{
                    title:"我的订单",
                    authRequire:true
                }
            },
            {
                path:"aftersale",
                name:"AfterSale",
                component:()=>import("@/components/personcenter/AfterSale.vue"),
                meta:{
                    title:"售后/退款",
                    authRequire:true
                }
            },
            {
                path:"userinfo",
                name:"UserInfo",
                component:()=>import("@/components/personcenter/UserInfo.vue"),
                meta:{
                    title:"个人信息",
                    authRequire:true
                }
            },
            {
                path:"useraccount",
                name:"UserAccount",
                component:()=>import("@/components/personcenter/UserAccount.vue"),
                meta:{
                    title:"账号绑定设置",
                    authRequire:true
                }
            },
            {
                path:"shopaddress",
                name:"ShopAddress",
                component:()=>import("@/components/personcenter/ShopAddress.vue"),
                meta:{
                    title:"收货地址"
                }
            },
            {
                path:"safecenter",
                name:"SafeCenter",
                component:()=>import("@/components/personcenter/SafeCenter.vue"),
                meta:{
                    title:"安全中心"
                }
            },
            {
                path:"usershop",
                name:"UserShop",
                component:()=>import("@/components/personcenter/userShop.vue"),
                meta:{
                    title:"已购商品"
                }
            },
            {
                path:"noticeprice",
                name:"NoticePrice",
                component:()=>import("@/components/personcenter/NoticePrice.vue"),
                meta:{
                    title:"降价通知"
                }
            },
            {
                path:"usercomment",
                name:"UserComment",
                component:()=>import("@/components/personcenter/UserComment.vue"),
                meta:{
                    title:"我的评论"
                }
            },
            {
                path:"usercollect",
                name:"UserCollect",
                component:()=>import("@/components/personcenter/UserCollect.vue"),
                meta:{
                    title:"我的收藏"
                }
            },
            {
                path:"userhelp",
                name:"UserHelp",
                component:()=>import("@/components/personcenter/UserHelp.vue"),
                meta:{
                    title:"帮助中心"
                }
            },

        ]
    },
]